[project]
name = "sim"
version = "1.0.0"
description = "A simulation environment manager"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["onshape-to-robot", "pyfqmr", "pypresence", "requests", "trimesh"]

[project.optional-dependencies]
reduce = ["open3d"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["cli", "cli.gazebo", "cli.gazebo.create", "cli.chrono"]

[tool.setuptools.package-data]
"cli.gazebo.create" = ["templates/**/*"]

[project.scripts]
sim = "cli.cli:main"
