#!/usr/bin/env bash
set -eu

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
docker_dir="$(cd "$script_dir/../docker" && pwd)"

defaults="$docker_dir/.env.defaults"
overrides="$docker_dir/.env.local"
env_out="$docker_dir/.env"

uname_s="$(uname -s 2>/dev/null || echo unknown)"

log() { printf "\033[1;36m%s\033[0m\n" "$1"; }

gpu_available() {
    [ "$uname_s" = "Linux" ] || return 1
    command -v nvidia-smi >/dev/null 2>&1 || return 1
    nvidia-smi -L >/dev/null 2>&1 || return 1
    docker info --format '{{json .Runtimes}}' 2>/dev/null | grep -q '"nvidia"' || return 1
}

gpu_runtime=""
gpu_available && gpu_runtime="nvidia"

# joystick passthrough
input_gid=""
[ "$uname_s" = "Linux" ] && input_gid="$(getent group input | cut -d: -f3 || true)"

write_display_env() {
    case "$uname_s" in
    Darwin)
        echo "# host: macOS (XQuartz over TCP + VirtualGL)"
        echo "DISPLAY=host.docker.internal:0"
        echo "VGL_DISPLAY=:88"
        echo "VGL_COMPRESS=proxy"
        ;;
    MINGW* | MSYS* | CYGWIN*)
        echo "# host: Windows (VcXsrv/X410 over TCP + VirtualGL)"
        echo "DISPLAY=host.docker.internal:0"
        echo "VGL_DISPLAY=:88"
        echo "VGL_COMPRESS=proxy"
        ;;
    Linux)
        echo "# host: Linux/WSLg (direct socket passthrough)"
        echo "DISPLAY=${DISPLAY:-:0}"
        ;;
    *)
        echo "# host: unknown ($uname_s) - falling back to local display :0"
        echo "DISPLAY=${DISPLAY:-:0}"
        ;;
    esac
}

write_env() {
    echo "# generated by .devcontainer/host-env.sh - do not edit or commit"
    echo "# to change ports/flags, edit docker/.env.defaults (shared) or docker/.env.local (yours)"
    echo ""

    cat "$defaults"

    if [ -f "$overrides" ]; then
        echo ""
        echo "# --- user overrides (docker/.env.local) ---"
        cat "$overrides"
    fi

    echo ""
    echo "# --- host-detected (generated, do not edit) ---"
    write_display_env
    echo "SIM_GPU_RUNTIME=$gpu_runtime"
    [ -n "$input_gid" ] && echo "INPUT_GID=$input_gid"

    if [ -n "$gpu_runtime" ]; then
        echo "NVIDIA_VISIBLE_DEVICES=all"
        echo "NVIDIA_DRIVER_CAPABILITIES=graphics,display,compute,utility"
        echo "__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json"
    fi
}

write_env >"$env_out"

echo "[INFO] host=$uname_s gpu=${gpu_runtime:-none}"
